FROM nginx:alpine
#RUN apk update  
#    apk add shadow 


RUN mkdir /www
RUN mkdir /www/html 
RUN mkdir /www/html/private
RUN mkdir /www/html/private/dist
#    mkdir /home/swuser/app 
#    groupadd -r swuser -g433 && \
#    useradd -u 431 -r -g swuser -d /home/swuser -s /sbin/nologin -c "Docker image user" swuser && \
#    chown -R swuser:swuser /home/swuser && \
#    chown -R swuser:swuser /home/swuser/app 


#EXPOSE 8080
EXPOSE 80

# RUN nginx
#EXPOSE 443

#USER swuser

WORKDIR /www/html
COPY index.html /www/html/private
COPY dist /www/html/private/dist
COPY nginx.conf /etc/nginx

# support running as arbitrary user which belogs to the root group
RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx

# users are not allowed to listen on priviliged ports
RUN sed -i.bak 's/listen\(.*\)80;/listen 8081;/' /etc/nginx/conf.d/default.conf
EXPOSE 8081

# comment user directive as master process is run as user in OpenShift anyhow
RUN sed -i.bak 's/^user/#user/' /etc/nginx/nginx.conf

RUN addgroup nginx root
USER nginx

#RUN chmod +x startskript.sh

#CMD /bin/sh startskript.sh
#CMD gunicorn -b "0.0.0.0:8080" test:app

CMD ["nginx", "-g", "daemon off;"]